// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArGJ-A_YOiFYKQh2UEkC2cdIPLn58yPf8',
    appId: '1:486361127786:web:e16ecc256b8ab45d2fa313',
    messagingSenderId: '486361127786',
    projectId: 'projectx-ff',
    authDomain: 'projectx-ff.firebaseapp.com',
    databaseURL: 'https://projectx-ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectx-ff.appspot.com',
    measurementId: 'G-S82NQGJ3J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5o7zoDD9e2YpSc9raL0fvVUXu1LhIiPk',
    appId: '1:486361127786:android:edff7b9149448b322fa313',
    messagingSenderId: '486361127786',
    projectId: 'projectx-ff',
    databaseURL: 'https://projectx-ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectx-ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwf44VRCM2xAAdYkZSgyV6vZ0nZpXpmnk',
    appId: '1:486361127786:ios:97f90d0643b3bb552fa313',
    messagingSenderId: '486361127786',
    projectId: 'projectx-ff',
    databaseURL: 'https://projectx-ff-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'projectx-ff.appspot.com',
    iosBundleId: 'com.example.projectx',
  );
}
